# Generated by Django 4.2.11 on 2024-04-15 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeUniversitaire',
            fields=[
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
                ('a', models.CharField(default='', max_length=9, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('niveau', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3')], max_length=2, primary_key=True, serialize=False, unique=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.anneeuniversitaire')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('nom', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], max_length=2, primary_key=True, serialize=False, unique=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('nom', models.CharField(default='A', max_length=5, primary_key=True, serialize=False)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.niveau')),
            ],
        ),
        migrations.AddField(
            model_name='filiere',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.niveau'),
        ),
    ]
