# Generated by Django 5.0.1 on 2024-03-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeUniversitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id_filiere', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id_groupe', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default='A', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id_niveau', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'M1'), ('M1', 'M2'), ('M3', 'D1'), ('D1', 'D2'), ('D2', 'D3')], max_length=2)),
            ],
        ),
    ]
