# Generated by Django 5.0.1 on 2024-03-18 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id_fichier', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.FileField(upload_to='fichiers/')),
                ('anne_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.anneeuniversitaire')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.filiere')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.groupe')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.niveau')),
            ],
        ),
    ]
