# Generated by Django 4.2.11 on 2024-04-15 06:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.FileField(upload_to='fichiers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'odt', 'ods', 'odp', 'zip', 'rar', 'tar', 'gz', 'bz2'])])),
                ('type', models.CharField(blank=True, max_length=100)),
                ('annee_universitaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.anneeuniversitaire')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.filiere')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.groupe')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.niveau')),
                ('s', models.ForeignKey(default='S1', on_delete=django.db.models.deletion.DO_NOTHING, to='reference.semester')),
            ],
        ),
    ]
