# Generated by Django 5.0.1 on 2024-03-18 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudient', '0003_alter_delegue_etudiant_alter_etudiant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegue',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='delegue',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='delegue',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='delegue',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='delegue',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='last_login',
        ),
    ]
