# Generated by Django 5.0.1 on 2024-03-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admini', '0002_alter_administrateur_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateur',
            name='nom',
        ),
        migrations.AlterField(
            model_name='administrateur',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
